version: '3'
services:
  food-app:
    build:
      context: ""
      dockerfile: ./Dockerfile
    working_dir: /home/node/app
    command: "pm2 restart ./apps.json && tail -f"
    volumes:
      - ../:/home/node/app
    tty: true
    container_name: food-app
    depends_on:
      - food-app-postgresql
    user: node

  food-app-postgresql:
    image: postgres:14-alpine
    container_name: food-app-postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"